language: android
sudo: false

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

android:
  components:
    - build-tools-26.0.1
    - android-26
    - extra

script:
  - ./gradlew build

notifications:
  email: false
